name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: First job script
        shell: bash
        run: echo Hello Nagasree
      - uses: actions/checkout@v4

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: Second job script
        shell: bash
        run: echo Hello Advaith


   
