name: first workflow

env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: First job script
        shell: bash
        run: echo Hello Nagasree
      - uses: actions/checkout@v4
      - name: Set time output
        id: print_to_log
        run: |
          echo "time=$(date)" >> $GITHUB_ENV  # Manually setting the output
          
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.print_to_log.outputs.time }}" # Using the output

  secondJob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This is job variable"
    steps:
      - name: Second job script
        shell: bash
        run: echo Hello Advaith
      - name: Environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ secrets.SOME_SECRET }}
          echo "The following are environment variables"
          echo $GITHUB_ACTOR
