name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: First job script
        shell: bash
        run: echo Hello Nagasree
      - uses: actions/checkout@v4
      - name: print to log
        id: print_to_log  # Corrected id (removed spaces and used underscore)
        uses: rajbos/actions-testing@v1

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: Second job script
        shell: bash
        run: echo Hello Advaith
